version: '3'

services:
  web:
    image: nginx
    ports:
      - 8000:8000
    env_file:
      - .env
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    restart: always

    # volumes:
    #   - .:/app